language: go

go:
- '1.9.x' # Google App Engine Standard Environment supports Go 1.9.

install:
- go get -v -t ./...

script:
- go test -v

before_install:
- openssl aes-256-cbc
  -K $encrypted_5b7fb06a6635_key -iv $encrypted_5b7fb06a6635_iv
  -in .service-account.json.enc -out .service-account.json -d

deploy:
  provider: gae
  keyfile: .service-account.json
  project: hangulize-api
