language: go

go:
- '1.9.x' # Google App Engine Standard Environment supports Go 1.9.

install:
- go get -v -t ./...
- go get github.com/gobuffalo/packr/...
- packr -i ../hangulize

script:
- go test -v ./v2

before_install:
- openssl aes-256-cbc
  -K $encrypted_5b7fb06a6635_key -iv $encrypted_5b7fb06a6635_iv
  -in .service-account.json.enc -out .service-account.json -d

deploy:
  provider: gae
  keyfile: .service-account.json
  project: hangulize-api
  default: true
