language: go

go:
- '1.12.x' # Google App Engine Standard Environment supports Go 1.12.

env:
- GO111MODULE=on

install:
- go get -v -t ./...

script:
- go test -v

after_success:
- go generate github.com/hangulize/hangulize

before_deploy:
- openssl aes-256-cbc -K $encrypted_5b7fb06a6635_key -iv $encrypted_5b7fb06a6635_iv -in .service-account.json.enc -out .service-account.json -d

deploy:
- provider: gae
  keyfile: .service-account.json
  project: hangulize-api
  on: master

- provider: gae
  keyfile: .service-account.json
  project: hangulize-api
  on:
    tags: true
