language: go

go:
- '1.12.x' # Google App Engine Standard Environment supports Go 1.12.

env:
- GO111MODULE=on

install:
- go get -v -t ./...

before_script:
# Install and activate Google Cloud SDK.
- pushd /tmp
- wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-276.0.0-linux-x86_64.tar.gz
- tar xzf google-cloud-sdk-276.0.0-linux-x86_64.tar.gz
- ./google-cloud-sdk/install.sh -q
- source ./google-cloud-sdk/path.bash.inc
- gcloud components install app-engine-python app-engine-go -q
- gcloud components update -q
- popd

script:
- go test -v

after_success:
- go generate github.com/hangulize/hangulize

before_deploy:
- openssl aes-256-cbc -K $encrypted_5b7fb06a6635_key -iv $encrypted_5b7fb06a6635_iv -in .service-account.json.enc -out .service-account.json -d

deploy:
- provider: gae
  keyfile: .service-account.json
  project: hangulize-api
  on: master

- provider: gae
  keyfile: .service-account.json
  project: hangulize-api
  on:
    tags: true
