runtime: go112

instance_class: F1

# There are 3 scaling policies in Google App Engine. But F1 instance class
# supports only automatic scaling. To enable Always Free, we must choose F1
# instance class.
#
# max_instances = min_instances = max_idle_instances = 1 is necessary to limit
# the number of actual instances by 1.
#
automatic_scaling:
  max_instances: 1
  min_instances: 1
  max_idle_instances: 1
  min_idle_instances: 1

inbound_services:
- warmup

main: .
