service: default

runtime: go
api_version: go1

instance_class: F1

automatic_scaling:
  max_instances: 1
  min_instances: 0
  max_idle_instances: 0

handlers:
- url: /.*
  script: _go_app
  secure: always
