service: furigana

runtime: go
api_version: go1

# High memory required due to the dictionary in Kagome.
instance_class: F2

automatic_scaling:
  max_instances: 1
  min_instances: 0

handlers:
- url: /.*
  script: _go_app
  secure: always
